---
- hosts: all
  become: yes
  tasks:

  - name: install mysql cluster package
    apt: state=present deb="/vagrant/mysql-cluster-gpl-7.4.10-debian7-x86_64.deb"

  - name: install libaio
    apt: state=present name=libaio1

  - name: install daemon
    apt: state=present name=daemon

- hosts: machine2, machine3, machine4, machine5
  become: yes
  tasks:

  - name: copy my.cnf
    copy: src=my.cnf dest=/etc/my.cnf

  
- hosts: machine1
  become: yes
  tasks:

  - name: create /var/lib/mysql-cluster
    file: path=/var/lib/mysql-cluster state=directory

  - name: install management node's config.ini
    copy: src=config.ini dest=/var/lib/mysql-cluster/config.ini

  - name: start management service
    shell: /opt/mysql/server-5.6/bin/ndb_mgmd -f /var/lib/mysql-cluster/config.ini


- hosts: machine2, machine3
  become: yes
  tasks:

  - name: create /var/lib/mysql-cluster
    file: path=/var/lib/mysql-cluster state=directory

  - shell: /opt/mysql/server-5.6/bin/ndbd


- hosts: machine4, machine5
  become: yes
  tasks:
  
  - name: create /opt/mysql/server-5.6/data/
    file: path=/opt/mysql/server-5.6/data/ state=directory owner=vagrant group=vagrant


- hosts: machine4, machine5
  tasks:
  - name: initialize the database
    shell: /opt/mysql/server-5.6/scripts/mysql_install_db

  - name: start mysql nodes
    shell: daemon -- /opt/mysql/server-5.6/bin/mysqld_safe


- hosts: machine4
  tasks:

  - name: move security tables into ndb 
    shell: /opt/mysql/server-5.6/bin/mysql -u root < /opt/mysql/server-5.6/share/ndb_dist_priv.sql

  - name: commit to new security tables
    shell: /opt/mysql/server-5.6/bin/mysql -u root -e "CALL mysql.mysql_cluster_move_privileges();" 


- hosts: machine4, machine5
  tasks:

  - name: flush security tables 
    shell: /opt/mysql/server-5.6/bin/mysql -u root -e "FLUSH PRIVILEGES;"
